#!/bin/sh

NAME=$(git branch | grep '*' | sed 's/* //')

# don't run on rebase
if [ "$NAME" != '(no branch)' ]
then
  git diff --name-only --cached | xargs git add
  git stash -q --keep-index
  npm run precommit

  RETVAL=$?

  if [ $RETVAL -ne 0 ]
  then
    exit 1
  fi

  git add .
  git stash pop -q
fi